---
- name: 'SwayWM: Install packages'
  become: true
  ansible.builtin.dnf:
    name:
      - '@swaywm-extended'
      - grimshot
      - glibc-langpack-sv   # Needed to properly display calendar in waybar.
    state: latest
  register: swaywm_packages

- name: 'SwayWM: Remove incompatible packages'
  become: true
  ansible.builtin.dnf:
    name:
      - volumeicon
    state: removed

- name: 'SwayWM: Remove obsolete configuration files'
  file:
    path: '{{ xdg_config_home }}/{{ item }}'
    state: absent
  with_items:
    - i3
    - i3status
    - sway/config

- name: 'SwayWM: Create directories'
  file:
    path: '{{ xdg_config_home }}/{{ item }}'
    state: directory
  with_items:
    - sway
    - sway/config.d
    - waybar

- name: 'SwayWM: Copy configuration files'
  copy:
    src: 'files/config/{{ item }}'
    dest: '{{ xdg_config_home }}/{{ item }}'
  register: swaywm_config
  with_items:
    - sway/config.d/font.conf
    - sway/config.d/keyboard.conf
    - sway/config.d/monitor.conf
    - sway/config.d/system-menu.conf
    - sway/config.d/95-xdg-user-dirs.conf
    - waybar/config.jsonc
    - waybar/style.css

- name: 'SwayWM: Restart sway'
  shell: swaymsg reload
  when:
    swaywm_packages.changed or swaywm_config.changed
...
