---
- name: 'SwayWM: Install packages'
  become: true
  ansible.builtin.dnf:
    name:
      - '@swaywm-extended'
      - gnome-terminal
      - cool-retro-term
    state: latest
  register: swaywm_packages

- name: 'SwayWM: Remove incompatible packages'
  become: true
  ansible.builtin.dnf:
    name:
      - volumeicon
    state: removed
  register: swaywm_packages

- name: 'SwayWM: Create directories'
  file:
    path: '{{ xdg_config_home }}/{{ item }}'
    state: directory
  with_items:
    - sway
    - i3status
    - i3status/scripts

- name: 'SwayWM: Copy configuration files'
  copy:
    src: 'files/config/{{ item.path }}'
    dest: '{{ xdg_config_home }}/{{ item.path }}'
    mode: '{{ item.mode }}'
  register: swaywm_config
  with_items:
    - { mode: '644', path: 'sway/config' }
    - { mode: '644', path: 'sway/background.png' }
    - { mode: '644', path: 'i3status/config' }
    - { mode: '755', path: 'i3status/scripts/wrapper.py' }

- name: 'SwayWM: Restart sway'
  shell: swaymsg reload
  when:
    swaywm_packages.changed or swaywm_config.changed
...
