---
- name: "i3wm: Install packages"
  become: true
  ansible.builtin.dnf:
    name:
      - "@i3-extended"
      - playerctl
      - volumeicon
      - gnome-terminal
      - cool-retro-term
    state: latest
  register: i3wm_packages

- name: "i3wm: Create directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/i3
    - ~/.config/i3status
    - ~/.config/i3status/scripts

- name: "i3wm: Copy configuration files"
  copy:
    src: "{{ item }}"
    dest: "~/.config/{{ item }}"
  register: i3wm_config
  with_items:
    - i3/config
    - i3/background.png
    - i3status/config

- name: "i3wm: Copy scripts"
  copy:
    src: "{{ item }}"
    dest: "~/.config/{{ item }}"
    mode: 0755
  register: i3wm_scripts
  with_items:
    - i3status/scripts/wrapper.py

- name: "i3wm: Restart i3"
  shell: "i3 restart"
  when:
    i3wm_packages.changed or i3wm_config.changed or i3wm_scripts.changed
...
