- name: 'volumeicon: Install packages'
  become: true
  ansible.builtin.dnf:
    name:
      - volumeicon
    state: latest

- name: 'volumeicon: Create directories'
  file:
    path: '{{ xdg_config_home }}/{{ item }}'
    state: directory
    recurse: yes
  with_items:
    - 'volumeicon'

- name: 'volumeicon: Copy configuration files'
  copy:
    src: 'files/config/{{ item.path }}'
    dest: '{{ xdg_config_home }}/{{ item.path }}'
    mode: '{{ item.mode }}'
  with_items:
    - { mode: '644', path: 'volumeicon/volumeicon' }
...
