---
- name: 'git: Install packages'
  become: true
  ansible.builtin.dnf:
    name:
      - git
    state: latest

- name: 'git: Create config directory'
  file:
    path: '{{ xdg_config_home }}/{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
  with_items:
    - { mode: '755', path: 'git' }

- name: 'git: Copy config files'
  copy:
    src: 'files/config/{{ item.path }}'
    dest: '{{ xdg_config_home }}/{{ item.path }}'
    mode: '{{ item.mode }}'
  with_items:
    - { mode: '644', path: 'git/config' }
...
