---
- name: 'Profile: Create directories'
  file:
    path: '{{ xdg_config_home }}/{{ item }}'
    state: directory
  with_items:
    - '{{ xdg_config_home }}/profile.d'
    - '~/.local/bin'

- name: 'Profile: Copy config files'
  copy:
    src: 'files/{{ item }}'
    dest: '~/{{ item }}'
    mode: '644'
  with_items:
    - .profile
    - .bash_profile
    - .bashrc
    - .local/bin/prompt.sh

...
