---
- name: 'Profile: Copy entry point .profile configuration'
  copy:
    src: 'files/{{ item }}'
    dest: '~/{{ item }}'
    mode: '644'
  with_items:
    - .profile
    - .bash_profile

- name: 'Profile: Create profile.d directory'
  file:
    path: '{{ xdg_config_home }}/{{ item }}'
    state: directory
    recurse: yes
  with_items:
    - profile.d
...
