---
- name: 'pass: Install packages'
  become: true
  ansible.builtin.dnf:
    name:
      - pass
    state: latest

- name: 'pass: Create config directory'
  file:
    path: '{{ xdg_config_home }}/{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
  with_items:
    - { mode: '700', path: 'password-store' }

- name: 'pass: Copy environment files'
  copy:
    src: 'files/config/{{ item.path }}'
    dest: '{{ xdg_config_home }}/{{ item.path }}'
    mode: '{{ item.mode }}'
  with_items:
    - { mode: '644', path: 'profile.d/pass.sh' }
...

# TODO: Set up git remote repo, config, etc.
