---
- name: 'i3wm: Install packages'
  become: true
  ansible.builtin.dnf:
    name:
      - '@i3-extended'
      - playerctl
      - gnome-terminal
      - cool-retro-term
    state: latest
  register: i3wm_packages

- name: 'i3wm: Create directories'
  file:
    path: '{{ xdg_config_home }}/{{ item }}'
    state: directory
  with_items:
    - i3
    - i3status
    - i3status/scripts

- name: 'i3wm: Copy configuration files'
  copy:
    src: 'files/config/{{ item.path }}'
    dest: '{{ xdg_config_home }}/{{ item.path }}'
    mode: '{{ item.mode }}'
  register: i3wm_config
  with_items:
    - { mode: '644', path: 'i3/config' }
    - { mode: '644', path: 'i3/background.png' }
    - { mode: '644', path: 'i3status/config' }
    - { mode: '755', path: 'i3status/scripts/wrapper.py' }

- name: 'i3wm: Restart i3'
  shell: i3 restart
  when:
    i3wm_packages.changed or i3wm_config.changed
...
