- name: 'foot: Install packages'
  become: true
  ansible.builtin.dnf:
    name:
      - foot
    state: latest

- name: 'foot: Create directories'
  file:
    path: '{{ xdg_config_home }}/{{ item }}'
    state: directory
  with_items:
    - foot

- name: 'foot: Copy configuration files'
  copy:
    src: 'files/config/{{ item.path }}'
    dest: '{{ xdg_config_home }}/{{ item.path }}'
    mode: '{{ item.mode }}'
  with_items:
    - { mode: '644', path: 'foot/foot.ini' }
...
